import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/modules/Header";
import Footer from "@/modules/Footer";

import StoreProvider from "../StoreProvider";

const interSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="ru">
      <body className={` ${interSans.variable} antialiased`}>
        <StoreProvider>
          <Header />
          {children}
          
          <Footer />
        </StoreProvider>
      </body>
   </html>
  );
}
